// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwinBlade.Infrastructure.Persistence.Rds;

#nullable disable

namespace TwinBlade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324083441_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwinBlade.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.PlayerProgress", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("HasBossCrard")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerProgresses");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.MatchResult", b =>
                {
                    b.OwnsMany("TwinBlade.Domain.Entities.PlayerMatchResult", "Players", b1 =>
                        {
                            b1.Property<Guid>("MatchResultId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("EarnedGold")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("MatchResultId", "Id");

                            b1.ToTable("PlayerMatchResult");

                            b1.WithOwner()
                                .HasForeignKey("MatchResultId");
                        });

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.PlayerProgress", b =>
                {
                    b.HasOne("TwinBlade.Domain.Entities.Player", null)
                        .WithOne("Progress")
                        .HasForeignKey("TwinBlade.Domain.Entities.PlayerProgress", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TwinBlade.Domain.Entities.PlayerItem", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("PlayerProgressPlayerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerProgressPlayerId", "Id");

                            b1.ToTable("PlayerItem");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProgressPlayerId");
                        });

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.Room", b =>
                {
                    b.OwnsMany("TwinBlade.Domain.Entities.RoomPlayer", "Players", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsReady")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.HasKey("RoomId", "Id");

                            b1.ToTable("RoomPlayer");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TwinBlade.Domain.Entities.Player", b =>
                {
                    b.Navigation("Progress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
